"
ExpressionStatements evaluated at the end of each loop
"
Class {
	#name : #FASTJavaIncrementorsStatement,
	#superclass : #MooseEntity,
	#category : 'FAST-Core-Model-Entities'
}

{ #category : #meta }
FASTJavaIncrementorsStatement class >> annotation [

	<MSEClass: #JavaIncrementorsStatement super: #MooseEntity>
	<package: #FAST>
	<generated>
	^self
]

{ #category : #generator }
FASTJavaIncrementorsStatement class >> generatedSlotNames [
	<generated>
	'FASTJavaIncrementorsStatement class>>#generatedSlotNames'.
	^ #()
]

{ #category : #generator }
FASTJavaIncrementorsStatement class >> generatedTraitNames [
	<generated>
	^ #()
]

{ #category : #meta }
FASTJavaIncrementorsStatement class >> metamodel [

	<generated>
	^ (self class environment at: #FASTJavaMetamodelGenerator) metamodel
]

{ #category : #meta }
FASTJavaIncrementorsStatement class >> requirements [

	<generated>
	^ {  }
]

{ #category : #testing }
FASTJavaIncrementorsStatement >> isAccess [

	<generated>
	^ false
]

{ #category : #testing }
FASTJavaIncrementorsStatement >> isAssociation [

	<generated>
	^ false
]

{ #category : #testing }
FASTJavaIncrementorsStatement >> isAttribute [

	<generated>
	^ false
]

{ #category : #testing }
FASTJavaIncrementorsStatement >> isClass [

	<generated>
	^ false
]

{ #category : #testing }
FASTJavaIncrementorsStatement >> isFunction [

	<generated>
	^ false
]

{ #category : #testing }
FASTJavaIncrementorsStatement >> isInheritance [

	<generated>
	^ false
]

{ #category : #testing }
FASTJavaIncrementorsStatement >> isInvocation [

	<generated>
	^ false
]

{ #category : #testing }
FASTJavaIncrementorsStatement >> isMethod [

	<generated>
	^ false
]

{ #category : #testing }
FASTJavaIncrementorsStatement >> isNamespace [

	<generated>
	^ false
]

{ #category : #testing }
FASTJavaIncrementorsStatement >> isPackage [

	<generated>
	^ false
]

{ #category : #testing }
FASTJavaIncrementorsStatement >> isReference [

	<generated>
	^ false
]

{ #category : #testing }
FASTJavaIncrementorsStatement >> isType [

	<generated>
	^ false
]
