"
A character literal
"
Class {
	#name : #FASTCharacterLiteral,
	#superclass : #FASTLiteral,
	#category : 'FAST-Core-Model-Entities'
}

{ #category : #meta }
FASTCharacterLiteral class >> annotation [

	<MSEClass: #CharacterLiteral super: #FASTLiteral>
	<package: #FAST>
	<generated>
	^self
]

{ #category : #generator }
FASTCharacterLiteral class >> generatedSlotNames [
	<generated>
	'FASTCharacterLiteral class>>#generatedSlotNames'.
	^ #()
]

{ #category : #generator }
FASTCharacterLiteral class >> generatedTraitNames [
	<generated>
	^ #()
]

{ #category : #meta }
FASTCharacterLiteral class >> requirements [

	<generated>
	^ {  }
]
