Trait {
	#name : #FASTTEntityMetaLevelDependency,
	#category : 'FAST-Core-Model-Traits'
}

{ #category : #meta }
FASTTEntityMetaLevelDependency classSide >> annotation [

	<MSEClass: #TEntityMetaLevelDependency super: #Trait>
	<generated>
	<package: #FAST>
	^self
]

{ #category : #generator }
FASTTEntityMetaLevelDependency classSide >> generatedSlotNames [
	<generated>
	'FASTTEntityMetaLevelDependency class>>#generatedSlotNames'.
	^ #()
]

{ #category : #generator }
FASTTEntityMetaLevelDependency classSide >> generatedTraitNames [
	<generated>
	^ #()
]
