Trait {
	#name : #FASTTDependencyQueries,
	#category : 'FAST-Core-Model-Traits'
}

{ #category : #meta }
FASTTDependencyQueries classSide >> annotation [

	<MSEClass: #TDependencyQueries super: #Trait>
	<generated>
	<package: #FAST>
	^self
]

{ #category : #generator }
FASTTDependencyQueries classSide >> generatedSlotNames [
	<generated>
	'FASTTDependencyQueries class>>#generatedSlotNames'.
	^ #()
]

{ #category : #generator }
FASTTDependencyQueries classSide >> generatedTraitNames [
	<generated>
	^ #()
]
