"
'null' literal in Java
"
Class {
	#name : #FASTJavaNullLiteral,
	#superclass : #FASTNullPointerLiteral,
	#category : 'FAST-Core-Model-Entities'
}

{ #category : #meta }
FASTJavaNullLiteral class >> annotation [

	<MSEClass: #JavaNullLiteral super: #FASTNullPointerLiteral>
	<package: #FAST>
	<generated>
	^self
]

{ #category : #generator }
FASTJavaNullLiteral class >> generatedSlotNames [
	<generated>
	'FASTJavaNullLiteral class>>#generatedSlotNames'.
	^ #()
]

{ #category : #generator }
FASTJavaNullLiteral class >> generatedTraitNames [
	<generated>
	^ #()
]

{ #category : #meta }
FASTJavaNullLiteral class >> requirements [

	<generated>
	^ {  }
]
