definition
defineNewClasses
	super defineNewClasses.
	javaAssignementExpression := builder newClassNamed: #JavaAssignementExpression.
	javaBreakStatement := builder newClassNamed: #JavaBreakStatement.
	javaCaseStatement := builder newClassNamed: #JavaCaseStatement.
	javaCharacterLiteral := builder newClassNamed: #JavaCharacterLiteral.
	javaContinueStatement := builder newClassNamed: #JavaContinueStatement.
	javaDoStatement := builder newClassNamed: #JavaDoStatement.
	javaFieldAccess := builder newClassNamed: #JavaFieldAccess.
	javaFloatLiteral := builder newClassNamed: #JavaFloatLiteral.
	javaForStatement := builder newClassNamed: #JavaForStatement.
	javaIdentifier := builder newClassNamed: #JavaIdentifier.
	javaIfStatement := builder newClassNamed: #JavaIfStatement.
	javaInfixOperation := builder newClassNamed: #JavaInfixOperation.
	javaIntegerLiteral := builder newClassNamed: #JavaIntegerLiteral.
	javaMethodEntity := builder newClassNamed: #JavaMethodEntity.
	javaMethodInvocation := builder newClassNamed: #JavaMethodInvocation.
	javaNullLiteral := builder newClassNamed: #JavaNullLiteral.
	javaSeparator := builder newClassNamed: #JavaSeparator.
	javaStringLiteral := builder newClassNamed: #JavaStringLiteral.
	javaSwitchStatement := builder newClassNamed: #JavaSwitchStatement.
	javaThis := builder newClassNamed: #JavaThis.
	javaVarDeclStatement := builder newClassNamed: #JavaVarDeclStatement.
	javaVariableDeclarator := builder newClassNamed: #JavaVariableDeclarator.
	javaWhileStatement := builder newClassNamed: #JavaWhileStatement