"
ExpressionStatements used at initialization phase of a for loop
"
Class {
	#name : #FASTJavaInitializersStatement,
	#superclass : #FASTStatement,
	#category : #'FAST-Core-Model-Entities'
}

{ #category : #meta }
FASTJavaInitializersStatement class >> annotation [

	<MSEClass: #JavaInitializersStatement super: #FASTStatement>
	<package: #FAST>
	<generated>
	^self
]

{ #category : #generator }
FASTJavaInitializersStatement class >> generatedSlotNames [
	<generated>
	'FASTJavaInitializersStatement class>>#generatedSlotNames'.
	^ #()
]

{ #category : #generator }
FASTJavaInitializersStatement class >> generatedTraitNames [
	<generated>
	^ #()
]

{ #category : #meta }
FASTJavaInitializersStatement class >> requirements [

	<generated>
	^ {  }
]
