"
A string in Java
"
Class {
	#name : #FASTJavaStringLiteral,
	#superclass : #FASTStringLiteral,
	#category : 'FAST-Core-Model-Entities'
}

{ #category : #meta }
FASTJavaStringLiteral class >> annotation [

	<MSEClass: #JavaStringLiteral super: #FASTStringLiteral>
	<package: #'FAST-Core-Model'>
	<generated>
	^self
]

{ #category : #generator }
FASTJavaStringLiteral class >> generatedSlotNames [
	<generated>
	'FASTJavaStringLiteral class>>#generatedSlotNames'.
	^ #()
]

{ #category : #generator }
FASTJavaStringLiteral class >> generatedTraitNames [
	<generated>
	^ #()
]

{ #category : #meta }
FASTJavaStringLiteral class >> requirements [

	<generated>
	^ {  }
]
