"
I represent the 'catch' part of the TryCatch Statement
"
Class {
	#name : #FASTJavaCatchPartStatement,
	#superclass : #FASTStatement,
	#category : #'FAST-Core-Model-Entities'
}

{ #category : #meta }
FASTJavaCatchPartStatement class >> annotation [

	<MSEClass: #JavaCatchPartStatement super: #FASTStatement>
	<package: #FAST>
	<generated>
	^self
]

{ #category : #generator }
FASTJavaCatchPartStatement class >> generatedSlotNames [
	<generated>
	'FASTJavaCatchPartStatement class>>#generatedSlotNames'.
	^ #()
]

{ #category : #generator }
FASTJavaCatchPartStatement class >> generatedTraitNames [
	<generated>
	^ #()
]

{ #category : #meta }
FASTJavaCatchPartStatement class >> requirements [

	<generated>
	^ {  }
]
