"
todo
"
Class {
	#name : #FASTJavaFloatLiteral,
	#superclass : #FASTLiteral,
	#category : 'FAST-Core-Model-Entities'
}

{ #category : #meta }
FASTJavaFloatLiteral class >> annotation [

	<MSEClass: #JavaFloatLiteral super: #FASTLiteral>
	<package: #'FAST-Core-Model'>
	<generated>
	^self
]

{ #category : #generator }
FASTJavaFloatLiteral class >> generatedSlotNames [
	<generated>
	'FASTJavaFloatLiteral class>>#generatedSlotNames'.
	^ #()
]

{ #category : #generator }
FASTJavaFloatLiteral class >> generatedTraitNames [
	<generated>
	^ #()
]

{ #category : #meta }
FASTJavaFloatLiteral class >> requirements [

	<generated>
	^ {  }
]
