"
I represent the 'try' part of the TryCatch Statement
"
Class {
	#name : #FASTJavaTryPartStatement,
	#superclass : #FASTStatement,
	#category : #'FAST-Core-Model-Entities'
}

{ #category : #meta }
FASTJavaTryPartStatement class >> annotation [

	<MSEClass: #JavaTryPartStatement super: #FASTStatement>
	<package: #FAST>
	<generated>
	^self
]

{ #category : #generator }
FASTJavaTryPartStatement class >> generatedSlotNames [
	<generated>
	'FASTJavaTryPartStatement class>>#generatedSlotNames'.
	^ #()
]

{ #category : #generator }
FASTJavaTryPartStatement class >> generatedTraitNames [
	<generated>
	^ #()
]

{ #category : #meta }
FASTJavaTryPartStatement class >> requirements [

	<generated>
	^ {  }
]
