"
case part of switch statement
"
Class {
	#name : #FASTJavaCaseStatement,
	#superclass : #FASTStatement,
	#category : 'FAST-Core-Model-Entities'
}

{ #category : #meta }
FASTJavaCaseStatement class >> annotation [

	<MSEClass: #JavaCaseStatement super: #FASTStatement>
	<package: #FAST>
	<generated>
	^self
]

{ #category : #generator }
FASTJavaCaseStatement class >> generatedSlotNames [
	<generated>
	'FASTJavaCaseStatement class>>#generatedSlotNames'.
	^ #()
]

{ #category : #generator }
FASTJavaCaseStatement class >> generatedTraitNames [
	<generated>
	^ #()
]

{ #category : #meta }
FASTJavaCaseStatement class >> requirements [

	<generated>
	^ {  }
]
