Class {
	#name : #FASTJavaThenPartStatement,
	#superclass : #MooseEntity,
	#category : 'FAST-Core-Model-Entities'
}

{ #category : #meta }
FASTJavaThenPartStatement class >> annotation [

	<MSEClass: #JavaThenPartStatement super: #MooseEntity>
	<package: #FAST>
	<generated>
	^self
]

{ #category : #generator }
FASTJavaThenPartStatement class >> generatedSlotNames [
	<generated>
	'FASTJavaThenPartStatement class>>#generatedSlotNames'.
	^ #()
]

{ #category : #generator }
FASTJavaThenPartStatement class >> generatedTraitNames [
	<generated>
	^ #()
]

{ #category : #meta }
FASTJavaThenPartStatement class >> metamodel [

	<generated>
	^ (self class environment at: #FASTJavaMetamodelGenerator) metamodel
]

{ #category : #meta }
FASTJavaThenPartStatement class >> requirements [

	<generated>
	^ {  }
]

{ #category : #testing }
FASTJavaThenPartStatement >> isAccess [

	<generated>
	^ false
]

{ #category : #testing }
FASTJavaThenPartStatement >> isAssociation [

	<generated>
	^ false
]

{ #category : #testing }
FASTJavaThenPartStatement >> isAttribute [

	<generated>
	^ false
]

{ #category : #testing }
FASTJavaThenPartStatement >> isClass [

	<generated>
	^ false
]

{ #category : #testing }
FASTJavaThenPartStatement >> isFunction [

	<generated>
	^ false
]

{ #category : #testing }
FASTJavaThenPartStatement >> isInheritance [

	<generated>
	^ false
]

{ #category : #testing }
FASTJavaThenPartStatement >> isInvocation [

	<generated>
	^ false
]

{ #category : #testing }
FASTJavaThenPartStatement >> isMethod [

	<generated>
	^ false
]

{ #category : #testing }
FASTJavaThenPartStatement >> isNamespace [

	<generated>
	^ false
]

{ #category : #testing }
FASTJavaThenPartStatement >> isPackage [

	<generated>
	^ false
]

{ #category : #testing }
FASTJavaThenPartStatement >> isReference [

	<generated>
	^ false
]

{ #category : #testing }
FASTJavaThenPartStatement >> isType [

	<generated>
	^ false
]
