"
A character in Java code
"
Class {
	#name : #FASTJavaCharacterLiteral,
	#superclass : #FASTCharacterLiteral,
	#category : 'FAST-Core-Model-Entities'
}

{ #category : #meta }
FASTJavaCharacterLiteral class >> annotation [

	<MSEClass: #JavaCharacterLiteral super: #FASTCharacterLiteral>
	<package: #'FAST-Core-Model'>
	<generated>
	^self
]

{ #category : #generator }
FASTJavaCharacterLiteral class >> generatedSlotNames [
	<generated>
	'FASTJavaCharacterLiteral class>>#generatedSlotNames'.
	^ #()
]

{ #category : #generator }
FASTJavaCharacterLiteral class >> generatedTraitNames [
	<generated>
	^ #()
]

{ #category : #meta }
FASTJavaCharacterLiteral class >> requirements [

	<generated>
	^ {  }
]
