Class {
	#name : #FASTJavaElsePartStatement,
	#superclass : #FASTStatement,
	#category : #'FAST-Core-Model-Entities'
}

{ #category : #meta }
FASTJavaElsePartStatement class >> annotation [

	<MSEClass: #JavaElsePartStatement super: #FASTStatement>
	<package: #FAST>
	<generated>
	^self
]

{ #category : #generator }
FASTJavaElsePartStatement class >> generatedSlotNames [
	<generated>
	'FASTJavaElsePartStatement class>>#generatedSlotNames'.
	^ #()
]

{ #category : #generator }
FASTJavaElsePartStatement class >> generatedTraitNames [
	<generated>
	^ #()
]

{ #category : #meta }
FASTJavaElsePartStatement class >> requirements [

	<generated>
	^ {  }
]
