Class {
	#name : #FASTSourceTextAnchor,
	#superclass : #FASTSourceAnchor,
	#traits : 'FamixTWithImmediateSource',
	#classTraits : 'FamixTWithImmediateSource classTrait',
	#category : #'FAST-Core-Model-Entities'
}

{ #category : #meta }
FASTSourceTextAnchor class >> annotation [

	<MSEClass: #SourceTextAnchor super: #FASTSourceAnchor>
	<package: #'FAST-Core-Model'>
	<generated>
	^self
]
