Class {
	#name : #FASTUnknownSourceLanguage,
	#superclass : #FASTSourceLanguage,
	#traits : 'FamixTUnknownSourceLanguage',
	#classTraits : 'FamixTUnknownSourceLanguage classTrait',
	#category : #'FAST-Core-Model-Entities'
}

{ #category : #meta }
FASTUnknownSourceLanguage class >> annotation [

	<FMClass: #UnknownSourceLanguage super: #FASTSourceLanguage>
	<package: #'FAST-Core-Model'>
	<generated>
	^self
]
