"
A node representing continue statement in java
"
Class {
	#name : #FASTJavaContinueStatement,
	#superclass : #FASTStatement,
	#category : 'FAST-Core-Model-Entities'
}

{ #category : #meta }
FASTJavaContinueStatement class >> annotation [

	<MSEClass: #JavaContinueStatement super: #FASTStatement>
	<package: #'FAST-Core-Model'>
	<generated>
	^self
]

{ #category : #generator }
FASTJavaContinueStatement class >> generatedSlotNames [
	<generated>
	'FASTJavaContinueStatement class>>#generatedSlotNames'.
	^ #()
]

{ #category : #generator }
FASTJavaContinueStatement class >> generatedTraitNames [
	<generated>
	^ #()
]

{ #category : #meta }
FASTJavaContinueStatement class >> requirements [

	<generated>
	^ {  }
]
