"
An undefined object literal
"
Class {
	#name : #FASTNullPointerLiteral,
	#superclass : #FASTLiteral,
	#category : #'FAST-Core-Model-Entities'
}

{ #category : #meta }
FASTNullPointerLiteral class >> annotation [

	<MSEClass: #NullPointerLiteral super: #FASTLiteral>
	<package: #'FAST-Core-Model'>
	<generated>
	^self
]

{ #category : #generator }
FASTNullPointerLiteral class >> generatedSlotNames [
	<generated>
	'FASTNullPointerLiteral class>>#generatedSlotNames'.
	^ #()
]

{ #category : #generator }
FASTNullPointerLiteral class >> generatedTraitNames [
	<generated>
	^ #()
]

{ #category : #meta }
FASTNullPointerLiteral class >> requirements [

	<generated>
	^ {  }
]
