"
A statement to ""interrupt"" a breakable statement like a break in Java loop or exit in fortran loop.
	(this is only a marker, there is no property attached to it)


"
Trait {
	#name : 'FASTTBreakStatement',
	#category : 'FAST-Core-Model-Traits',
	#package : 'FAST-Core-Model',
	#tag : 'Traits'
}

{ #category : 'meta' }
FASTTBreakStatement classSide >> annotation [

	<FMClass: #TBreakStatement super: #Object>
	<package: #'FAST-Core-Model'>
	<generated>
	^ self
]
