"
A node representing break statement in java
"
Class {
	#name : #FASTJavaBreakStatement,
	#superclass : #FASTStatement,
	#category : 'FAST-Core-Model-Entities'
}

{ #category : #meta }
FASTJavaBreakStatement class >> annotation [

	<MSEClass: #JavaBreakStatement super: #FASTStatement>
	<package: #'FAST-Core-Model'>
	<generated>
	^self
]

{ #category : #generator }
FASTJavaBreakStatement class >> generatedSlotNames [
	<generated>
	'FASTJavaBreakStatement class>>#generatedSlotNames'.
	^ #()
]

{ #category : #generator }
FASTJavaBreakStatement class >> generatedTraitNames [
	<generated>
	^ #()
]

{ #category : #meta }
FASTJavaBreakStatement class >> requirements [

	<generated>
	^ {  }
]
