"
A representation of a variable entity, 
"
Class {
	#name : #FASTVariableEntity,
	#superclass : #FASTStatement,
	#traits : 'FamixTNamedEntity',
	#classTraits : 'FamixTNamedEntity classTrait',
	#category : #'FAST-Core-Model-Entities'
}

{ #category : #meta }
FASTVariableEntity class >> annotation [

	<FMClass: #VariableEntity super: #FASTStatement>
	<package: #'FAST-Core-Model'>
	<generated>
	^self
]
