@startuml

hide empty members

class behavior1 as "Entity" {
}

class behavior2 as "SourceAnchor" {
}

class behavior3 as "SourceLanguage / TSourceLanguage" {
}

class behavior4 as "SourcedEntity" {
}

class behavior5 as "EntitySourceAnchor / TSourceAnchor" {
	- Number startPos
	- Number endPos
}

class behavior6 as "Association" {
}

class behavior7 as "Comment / TComment" {
}

class behavior8 as "NamedEntity" {
}

class behavior9 as "SourceTextAnchor / TWithImmediateSource" {
}

class behavior10 as "Expression" {
}

class behavior11 as "ScopableEntity" {
}

class behavior12 as "Literal" {
	- String value
}

class behavior13 as "VariableExpression" {
}

class behavior14 as "BehaviouralEntity" {
}

class behavior15 as "Statement" {
}

class behavior16 as "BooleanLiteral" {
}

class behavior17 as "CharacterLiteral" {
}

class behavior18 as "NullPointerLiteral" {
}

class behavior19 as "StringLiteral" {
}

class behavior20 as "NamedBehaviouralEntity" {
}

class behavior21 as "ExpressionStatement" {
}

class behavior22 as "ReturnStatement" {
}

class behavior23 as "StatementBlock" {
}

class behavior24 as "VariableEntity" {
}

behavior1 <|-- behavior2
behavior1 <|-- behavior3
behavior1 <|-- behavior4
behavior1 <|-- behavior5
behavior4 <|-- behavior6
behavior4 <|-- behavior7
behavior5 <|-- behavior8
behavior2 <|-- behavior9
behavior5 <|-- behavior10
behavior5 <|-- behavior11
behavior10 <|-- behavior12
behavior10 <|-- behavior13
behavior11 <|-- behavior14
behavior11 <|-- behavior15
behavior12 <|-- behavior16
behavior12 <|-- behavior17
behavior12 <|-- behavior18
behavior12 <|-- behavior19
behavior14 <|-- behavior20
behavior15 <|-- behavior21
behavior15 <|-- behavior22
behavior15 <|-- behavior23
behavior15 <|-- behavior24

behavior15 "statements * " -[#red]-o "statementContainer  " behavior23
behavior14 "parentBehaviouralEntity  " o-[#red]- "parameters * " behavior13
behavior21 "expressionStatementOwner  " o-[#red]- "expression  " behavior10
behavior14 "fastBehaviouralParent  " o-[#red]- "statementBlock  " behavior23
behavior22 "returnOwner  " o-[#red]- "expression  " behavior10

@enduml
