definition
defineProperties
	(variableEntity property: #variableName type: #String) comment: 'Name of a variable'.
	(namedBehaviouralEntity property: #behaviouralName type: #String) comment: 'Name of the behavioural entity'.
	(variableExpression property: #variableName type: #String) comment: 'Name of a variable'.
	(literal property: #value type: #String) comment: 'The literal itself as found in the source code'